apiVersion: apps/v1
kind: Deployment
metadata:
  name: api1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api1-pod
  template:
    metadata:
      labels:
        app: api1-pod
    spec:
      #nodeSelector:
      #  "beta.kubernetes.io/os": linux
      containers:
      - name: api1-container
        image: docker pull 45862391/aksdemo.api1:1.0.0
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 6379
          name: api1
---
apiVersion: v1
kind: Service
metadata:
  name: api1
spec:
  ports:
  - port: 6379
  selector:
    app: api1